#
# Module manifest for module 'MarkX'
#
# Generated by: James Brundage
#
# Generated on: 12/23/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'MarkX.psm1'

# Version number of this module.
ModuleVersion = '0.1.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '1d54ba10-9f15-4f1f-bf5b-8b2fff02927b'

# Author of this module
Author = 'James Brundage'

# Company or vendor of this module
CompanyName = 'Start Automating'

# Copyright statement for this module
Copyright = '2025 Start Automating'

# Description of the functionality provided by this module
Description = 'MarkX - Markdown, XML, and PowerShell'

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @('MarkX.types.ps1xml')

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @('MarkX.format.ps1xml')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-MarkX'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'MarkX', 'Markdown', 'Get-Markdown'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @()

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/StartAutomating/MarkX/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/StartAutomating/MarkX'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
## MarkX 0.1.1:

* MarkX Help (#26)
* MarkX now accepts commands / help (#27)
* MarkX.Headings gets heading elements (#29)
* MarkX.Lexicon gets lexicons in Markdown (#25)
* MarkX.YamlHeader support (#32, #33)
* Allowing piped markdown file input (#34)
* MarkX.Code gets code within markdown (#30)
* MarkX.CodeBlock gets code blocks within markdown (#31)
* MarkX.ToString can now stringify any property (#35)
* MarkX formatting (#36)

---

Additional release notes in [CHANGELOG](https://github.com/StartAutomating/MarkX/blob/main/CHANGELOG.md)
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

